### ISSUE TITLE
[bug] problem when parsing schema with joi.alternatives().conditional()

### ISSUE THREAD

**Issue by bigLucas** [kenspirit/joi-to-json#24] opened 2022-04-05 04:43 UTC
For some reason I'm getting an error when parsing a schema with `joi.alternatives().conditional()`, example:
```javascript
import joi from 'joi';
import parse from 'joi-to-json';

const joiSchema = joi.object().keys({
    userName: joi.string().not().empty().required(),
    partner: joi.string()
        .not()
        .empty()
        .valid('cool_partner', 'other')
        .required(),
    password: joi.alternatives().conditional('partner', {
        is: 'cool_partner',
        then: joi.string().not().empty().required(),
        otherwise: joi.optional()
    })
});

console.log(parse(joiSchema));
```
With this error:
```shell
TypeError: Cannot read properties of undefined (reading 'type')
```

joi version: 17.6.0
joi-to-json verison: 2.2.0
Node.js version: 16.14.0

Removing the `password` property removes the error.

Do you have some idea about this?
Am I using in the wrong way the libraries?

**Comment by kenspirit** [comment] 2022-04-06 13:58
Hi @bigLucas, the issue is fixed in version 2.2.1.  Thanks for your support.

**Closed by kenspirit** 2022-04-06 13:58 UTC
